Repository newrelic-experimental/newrelic-social-listening-service-nodejs, pull requests merged in 2020-09, with the labels that each got.

#19 feat(release drafter): automatic release drafting on push to main
  .github/release-drafter.yml
  .github/workflows/release-drafter.yml
  branchlint.json
Labels: feature, minor

#22 documentation(readme): readme corrections
  README.md
Labels: documentation

#23 bugfix(metric client): fix memory leak when sending data to new relic
  .github/workflows/continuous-integration.yml
  app/app.ts
  app/lib/MetricClient.test.ts
  app/lib/MetricClient.ts
  package-lock.json
  package.json
Labels: bugfix

#24 enhancement(ci repolinter): add open source policy workflow
  .github/workflows/repolinter.yml
Labels: enhancement

#26 feat(docker): docker prod deployment
  Dockerfile
  docker-compose.yml
  package.json
Labels: enhancement
